export interface AbdomenQuestion {
  id: number;
  spotter: string;
  structureName: string;
  questionA: string;
  questionB: string;
  answerA: string;
  answerB: string;
}

export const ABDOMEN_QUESTIONS: AbdomenQuestion[] = [
  {
    id: 1,
    spotter: "ABD-1",
    structureName: "Appendix",
    questionA: "Identify the tied structure.",
    questionB: "Give its positions, blood supply and applied anatomy.",
    answerA: "Appendix",
    answerB: "Positions: paracolic (11 o'clock), retrocaecal (12 o'clock — commonest), splenic (2 o'clock), promontoric (3 o'clock), pelvic (4 o'clock — 2nd commonest), midinguinal (6 o'clock). Blood supply: appendicular artery — branch of ileocolic artery from SMA. Applied: Appendicitis; McBurney's point at junction of lateral ⅔ and medial ⅓ of line joining RASIS and umbilicus.",
  },
  {
    id: 2,
    spotter: "ABD-2",
    structureName: "Caecum",
    questionA: "Identify the pinned structure.",
    questionB: "Give its posterior relations.",
    answerA: "Caecum",
    answerB: "Posterior relations: (1) Muscles — right psoas and right iliacus. (2) Nerves — genitofemoral, femoral, and lateral cutaneous nerve of thigh. (3) Vessels — testicular or ovarian. (4) Appendix in the retrocaecal recess.",
  },
  {
    id: 3,
    spotter: "ABD-3",
    structureName: "Gall Bladder",
    questionA: "Identify the pinned structure.",
    questionB: "Give its parts, capacity and applied anatomy.",
    answerA: "Gall bladder",
    answerB: "Parts: fundus, body and neck. Capacity: 30–50 ml. Applied anatomy: cholecystitis, cholelithiasis.",
  },
  {
    id: 4,
    spotter: "ABD-4",
    structureName: "Greater Curvature of Stomach",
    questionA: "Identify the pinned area of the given organ.",
    questionB: "Name the structures attached and present in it.",
    answerA: "Greater curvature of stomach",
    answerB: "Structures attached: greater omentum, gastrosplenic ligament, gastrophrenic ligament. Structures present: right and left gastroepiploic arteries.",
  },
  {
    id: 5,
    spotter: "ABD-5",
    structureName: "Greater Omentum",
    questionA: "Identify the pinned structure.",
    questionB: "Name the structures present in it.",
    answerA: "Greater omentum",
    answerB: "Structures present: right and left gastroepiploic arteries.",
  },
  {
    id: 6,
    spotter: "ABD-6",
    structureName: "Hilum of Spleen",
    questionA: "Identify the pinned structure.",
    questionB: "Name the structures present in it.",
    answerA: "Hilum of spleen",
    answerB: "Structures present: splenic vessels and nerve; gives attachment to gastrosplenic ligament and lienorenal ligament.",
  },
  {
    id: 7,
    spotter: "ABD-7",
    structureName: "Ileo-Caecal Orifice",
    questionA: "Identify the pinned structure.",
    questionB: "Give its functions.",
    answerA: "Ileo-caecal orifice",
    answerB: "Functions: (1) Prevents reflux from caecum to ileum. (2) Regulates the passage of ileal contents into the caecum and prevents them from passing too quickly.",
  },
  {
    id: 8,
    spotter: "ABD-8",
    structureName: "Visceral Impressions of Liver",
    questionA: "Identify the structures present on the pinned area.",
    questionB: "Name all coloured impressions (red, light blue, black & orange, yellow, green, dark blue, *).",
    answerA: "Visceral impressions on the inferior surface of liver",
    answerB: "Red — oesophagus. Light blue — gastric impression (stomach). Black & orange — pylorus of stomach. Yellow — colic impression (hepatic flexure). Green — right kidney. Dark blue — right suprarenal gland. * — first part of duodenum.",
  },
  {
    id: 9,
    spotter: "ABD-9",
    structureName: "Visceral Impressions of Spleen",
    questionA: "Identify the structures present on the pinned area.",
    questionB: "Name all coloured impressions (yellow, orange, red, green).",
    answerA: "Visceral impressions on the medial surface of spleen",
    answerB: "Yellow — gastric impression (fundus of stomach). Orange — renal impression (left kidney). Red — pancreatic impression (tail of pancreas). Green — colic impression (splenic flexure of colon).",
  },
  {
    id: 10,
    spotter: "ABD-10",
    structureName: "Jejunum and Ileum",
    questionA: "Identify the organs.",
    questionB: "Give the differences between jejunum and ileum.",
    answerA: "Jejunum (upper) and ileum (lower)",
    answerB: "Jejunum — upper & left, thicker wall, wider lumen often empty, mesentery windows present, 1–2 arterial arcades, longer vasa recta, larger circular folds, larger villi, no Peyer's patches. Ileum — lower & right, thinner wall, narrower often loaded, no windows, 3–5 arcades, shorter more numerous vasa recta, Peyer's patches present.",
  },
  {
    id: 11,
    spotter: "ABD-11",
    structureName: "Large Intestine",
    questionA: "Identify the organ.",
    questionB: "Give its cardinal features and parts.",
    answerA: "Large intestine",
    answerB: "Cardinal features: (1) Taenia coli. (2) Appendices epiploicae. (3) Sacculations / haustrations. Parts: caecum, appendix, ascending colon, transverse colon, descending colon, sigmoid colon, rectum and anal canal.",
  },
  {
    id: 12,
    spotter: "ABD-12",
    structureName: "Lesser Curvature of Stomach",
    questionA: "Identify the pinned area of the given organ.",
    questionB: "Name the structures attached to it and present in it.",
    answerA: "Lesser curvature of stomach",
    answerB: "Structure attached: lesser omentum. Structure present in it: right and left gastric arteries.",
  },
  {
    id: 13,
    spotter: "ABD-13",
    structureName: "Lesser Omentum",
    questionA: "Identify the pinned structure.",
    questionB: "Name the structures present in it.",
    answerA: "Lesser omentum",
    answerB: "Structures present: right and left gastric arteries.",
  },
  {
    id: 14,
    spotter: "ABD-14",
    structureName: "Ligamentum Teres",
    questionA: "Identify the tied structure.",
    questionB: "Give its embryological significance.",
    answerA: "Ligamentum teres of liver",
    answerB: "Embryological significance: remnant of the obliterated left umbilical vein.",
  },
  {
    id: 15,
    spotter: "ABD-15",
    structureName: "Ligamentum Venosum",
    questionA: "Identify the pinned structure.",
    questionB: "Give its embryological significance.",
    answerA: "Ligamentum venosum",
    answerB: "Embryological significance: remnant of ductus venosus, which connects the left branch of portal vein with the inferior vena cava during foetal life.",
  },
  {
    id: 16,
    spotter: "ABD-16",
    structureName: "Major Duodenal Papilla",
    questionA: "Identify the pinned structure.",
    questionB: "What opens into it and at what position is it located?",
    answerA: "Major duodenal papilla",
    answerB: "Hepatopancreatic ampulla opens into it (union of bile duct and main pancreatic duct). Location: 8–10 cm distal to the pylorus on the medial wall of the second part of duodenum.",
  },
  {
    id: 17,
    spotter: "ABD-17",
    structureName: "Mesentery",
    questionA: "Identify the pinned structure.",
    questionB: "Give its extent, contents and structures crossed by it.",
    answerA: "Mesentery",
    answerB: "Extent: duodenojejunal flexure (L2, left side) to ileocaecal junction (right sacro-iliac joint). Contents: jejunal & ileal branches of SMA with veins, autonomic plexuses, lymphatics, 100–200 lymph nodes, fat. Structures crossed: 3rd part of duodenum, abdominal aorta, IVC, right ureter, right psoas major.",
  },
  {
    id: 18,
    spotter: "ABD-18",
    structureName: "Pancreas",
    questionA: "Identify the pinned structure.",
    questionB: "Give its parts, blood supply, applied anatomy and development.",
    answerA: "Pancreas",
    answerB: "Parts: head, neck, body and tail. Blood supply: superior & inferior pancreaticoduodenal arteries, pancreatic branches of splenic artery. Applied: pancreatitis, annular pancreas, pancreatic cyst, carcinoma head of pancreas. Development: from dorsal and ventral pancreatic buds (both foregut and midgut).",
  },
  {
    id: 19,
    spotter: "ABD-19",
    structureName: "Porta Hepatis",
    questionA: "Identify the pinned structure.",
    questionB: "Name the structures present in it in order from behind forwards.",
    answerA: "Porta hepatis of liver",
    answerB: "From behind forwards: (1) Portal vein. (2) Hepatic artery. (3) Hepatic duct.",
  },
  {
    id: 20,
    spotter: "ABD-20",
    structureName: "Second Part of Duodenum",
    questionA: "Identify the pinned area.",
    questionB: "Describe its interior, blood supply, development and applied anatomy.",
    answerA: "Second part of duodenum",
    answerB: "Interior: major duodenal papilla (8–10 cm from pylorus — hepatopancreatic ampulla) and minor duodenal papilla (6–8 cm — accessory pancreatic duct). Blood supply: superior & inferior pancreaticoduodenal arteries. Development: upper half (to bile duct opening) = foregut; lower half = midgut. Applied: congenital stenosis and obstruction from annular pancreas.",
  },
  {
    id: 21,
    spotter: "ABD-21",
    structureName: "Spleen",
    questionA: "Identify the given organ.",
    questionB: "Name the ligaments related to it and give its blood supply.",
    answerA: "Spleen — visceral surface",
    answerB: "Ligaments: (1) Gastrosplenic ligament. (2) Lienorenal ligament. (3) Phrenicolic ligament. Blood supply: splenic artery and splenic vein.",
  },
  {
    id: 22,
    spotter: "ABD-22",
    structureName: "Stomach",
    questionA: "Identify the organ.",
    questionB: "Give its parts, blood supply and applied anatomy.",
    answerA: "Stomach",
    answerB: "Parts: cardiac part (fundus & body), pyloric part (pyloric antrum & pyloric canal). Blood supply — arterial: right & left gastric, right & left gastroepiploic, short gastric arteries. Venous: portal vein, splenic vein, SMV. Applied: gastric ulcer, gastric carcinoma.",
  },
  {
    id: 23,
    spotter: "ABD-23",
    structureName: "Abdominal Aorta",
    questionA: "Identify the tied structure.",
    questionB: "Give its extent, branches and terminal branches.",
    answerA: "Abdominal aorta",
    answerB: "Extent: lower border T12 to lower body L4. Branches — ventral: coeliac trunk, SMA, IMA; lateral: inferior phrenic, renal, middle suprarenal, gonadal arteries; dorsal: lumbar arteries, median sacral artery. Terminal branches: right and left common iliac arteries.",
  },
  {
    id: 24,
    spotter: "ABD-24",
    structureName: "Broad Ligament of Uterus",
    questionA: "Identify the pinned structure.",
    questionB: "Give its contents.",
    answerA: "Broad ligament of uterus",
    answerB: "Contents: (1) Uterine tube. (2) Round ligament of uterus. (3) Ligament of the ovary. (4) Uterine vessels. (5) Ovarian vessels. (6) Uterovaginal and ovarian nerve plexus. (7) Epoophoron. (8) Paroophoron. (9) Lymph nodes. (10) Parametrium (dense connective tissue).",
  },
  {
    id: 25,
    spotter: "ABD-25",
    structureName: "Diaphragm",
    questionA: "Identify the pinned structure.",
    questionB: "Give its major openings with levels, parts, nerve supply and development.",
    answerA: "Diaphragm",
    answerB: "Major openings: IVC — T8; oesophagus — T10; abdominal aorta — T12. Parts: sternal, costal and lumbar. Nerve supply: phrenic nerve (C3, C4, C5). Development: septum transversum (central tendon), pleuroperitoneal membranes (dorsal paired), lateral thoracic wall (circumferential), dorsal mesentery of oesophagus (dorsal unpaired).",
  },
  {
    id: 26,
    spotter: "ABD-26",
    structureName: "Femoral Nerve",
    questionA: "Identify the tied structure.",
    questionB: "What is it a branch of and give its root value?",
    answerA: "Femoral nerve",
    answerB: "Branch of the lumbar plexus. Root value: dorsal divisions of anterior primary rami of L2, L3, L4.",
  },
  {
    id: 27,
    spotter: "ABD-27",
    structureName: "Genitofemoral Nerve",
    questionA: "Identify the tied structure.",
    questionB: "What is it a branch of and give its root value?",
    answerA: "Genitofemoral nerve",
    answerB: "Branch of the lumbar plexus. Root value: ventral divisions of anterior primary rami of L1, L2.",
  },
  {
    id: 28,
    spotter: "ABD-28",
    structureName: "Hilum of Left Kidney",
    questionA: "Identify the side and the pinned area of the given organ.",
    questionB: "Name the structures present in it in order from anterior to posterior.",
    answerA: "Hilum of left kidney",
    answerB: "From anterior to posterior: (1) Renal vein. (2) Renal artery. (3) Renal pelvis.",
  },
  {
    id: 29,
    spotter: "ABD-29",
    structureName: "Iliacus",
    questionA: "Identify the pinned structure.",
    questionB: "Give its attachments, nerve supply and actions.",
    answerA: "Iliacus",
    answerB: "Origin: upper ⅔ of iliac fossa, inner lip of iliac crest, upper surface of lateral sacrum. Insertion: lesser trochanter of femur. Nerve supply: branch from femoral nerve (L2, L3). Action: flexion of hip joint.",
  },
  {
    id: 30,
    spotter: "ABD-30",
    structureName: "Inferior Vena Cava",
    questionA: "Identify the tied structure.",
    questionB: "Give its formation, termination and tributaries.",
    answerA: "Inferior vena cava (IVC)",
    answerB: "Formation: union of right and left common iliac veins. Termination: lower and posterior part of right atrium. Tributaries: 3rd & 4th lumbar veins, right testicular/ovarian vein, renal veins, right suprarenal vein, hepatic veins.",
  },
  {
    id: 31,
    spotter: "ABD-31",
    structureName: "Internal Iliac Artery",
    questionA: "Identify the tied structure.",
    questionB: "Give any 4 branches from both divisions.",
    answerA: "Internal iliac artery",
    answerB: "Anterior division: superior vesical, obturator, middle rectal, inferior vesical (vaginal A in females), inferior gluteal, internal pudendal, uterine (females). Posterior division: iliolumbar, lateral sacral, superior gluteal arteries.",
  },
  {
    id: 32,
    spotter: "ABD-32",
    structureName: "Intervertebral Disc",
    questionA: "Identify the pinned structure.",
    questionB: "Give its parts and type of joint.",
    answerA: "Intervertebral disc",
    answerB: "Parts: (1) Annulus fibrosus (outer fibrocartilaginous ring). (2) Nucleus pulposus (inner gelatinous core). Type of joint: secondary cartilaginous joint (symphysis).",
  },
  {
    id: 33,
    spotter: "ABD-33",
    structureName: "Median Umbilical Ligament",
    questionA: "Identify the tied structure.",
    questionB: "Give its embryological significance.",
    answerA: "Median umbilical ligament",
    answerB: "Embryological significance: remnant of the urachus (allantois), connecting the apex of the urinary bladder to the umbilicus.",
  },
  {
    id: 34,
    spotter: "ABD-34",
    structureName: "Obturator Nerve",
    questionA: "Identify the tied structure.",
    questionB: "What is it a branch of and give its root value?",
    answerA: "Obturator nerve",
    answerB: "Branch of the lumbar plexus. Root value: ventral divisions of anterior primary rami of L2, L3, L4.",
  },
  {
    id: 35,
    spotter: "ABD-35",
    structureName: "Ovary",
    questionA: "Identify the pinned structure.",
    questionB: "Give its position and blood supply.",
    answerA: "Ovary",
    answerB: "Position: ovarian fossa in the lateral pelvic wall — anterior boundary: obliterated umbilical artery; posterior: ureter and internal iliac artery. Blood supply — arterial: ovarian artery and uterine artery. Venous drainage: pampiniform plexus of veins.",
  },
  {
    id: 36,
    spotter: "ABD-36",
    structureName: "Pouch of Douglas",
    questionA: "Identify the probed space.",
    questionB: "Give its boundaries and applied anatomy.",
    answerA: "Pouch of Douglas (rectouterine pouch)",
    answerB: "Boundaries — anterior: uterus and posterior fornix of vagina; posterior: rectum; inferior: rectovaginal fold of peritoneum. Applied anatomy: pus tends to collect here as it is the most dependent part of the peritoneal cavity in the erect position.",
  },
  {
    id: 37,
    spotter: "ABD-37",
    structureName: "Prostate Gland",
    questionA: "Identify the pinned structure.",
    questionB: "Give its lobes and applied anatomy.",
    answerA: "Prostate gland",
    answerB: "Lobes: 5 lobes — anterior, posterior, two lateral lobes and median lobe. Applied anatomy: carcinoma of prostate (posterior lobe), benign prostatic hypertrophy (median lobe).",
  },
  {
    id: 38,
    spotter: "ABD-38",
    structureName: "Prostate Gland (Sagittal Section)",
    questionA: "Identify the pinned structure.",
    questionB: "Give its lobes and applied anatomy.",
    answerA: "Prostate gland — sagittal section",
    answerB: "Lobes: 5 lobes — anterior, posterior, two lateral lobes and median lobe. Applied anatomy: carcinoma of prostate (posterior lobe), benign prostatic hypertrophy (median lobe).",
  },
  {
    id: 39,
    spotter: "ABD-39",
    structureName: "Prostatic Urethra",
    questionA: "Identify the pinned structure.",
    questionB: "Name the structures opening into it.",
    answerA: "Prostatic urethra",
    answerB: "Structures opening into it: (1) Prostatic utricle. (2) Ejaculatory ducts. (3) Prostatic glands.",
  },
  {
    id: 40,
    spotter: "ABD-40",
    structureName: "Psoas Major",
    questionA: "Identify the pinned structure.",
    questionB: "Give its attachments, nerve supply and actions.",
    answerA: "Psoas major",
    answerB: "Origin: anterior surface & lower border of transverse processes of all lumbar vertebrae; bodies of adjacent vertebrae & IVDs (5 slips, T12–L5); 4 tendinous arches (L. border T12 to U. border L5). Insertion: lesser trochanter of femur. Nerve: branches from L2, L3, L4. Action: flexion of hip joint; weak medial rotation.",
  },
  {
    id: 41,
    spotter: "ABD-41",
    structureName: "Psoas Major (Alt. View)",
    questionA: "Identify the pinned structure.",
    questionB: "Give its attachments, nerve supply and actions.",
    answerA: "Psoas major",
    answerB: "Origin: transverse processes of all lumbar vertebrae; vertebral bodies & IVDs (T12–L5); 4 tendinous arches. Insertion: lesser trochanter of femur. Nerve supply: L2, L3, L4 spinal nerve branches. Action: flexion of hip joint; weak medial rotation.",
  },
  {
    id: 42,
    spotter: "ABD-42",
    structureName: "Pubic Symphysis",
    questionA: "Identify the pinned structure.",
    questionB: "What type of joint is it?",
    answerA: "Pubic symphysis",
    answerB: "Type of joint: secondary cartilaginous joint (symphysis). It contains a fibrocartilaginous disc between the two pubic bones.",
  },
  {
    id: 43,
    spotter: "ABD-43",
    structureName: "Rectum",
    questionA: "Identify the pinned structure.",
    questionB: "Give its blood supply and supports.",
    answerA: "Rectum",
    answerB: "Blood supply — arterial: superior rectal, middle rectal, median sacral arteries. Venous: superior & middle rectal veins, median sacral vein. Supports: (1) Pelvic floor — levator ani. (2) Fascia of Waldeyer. (3) Lateral ligaments of rectum. (4) Rectovesical fascia of Denonvilliers. (5) Pelvic peritoneum. (6) Perineal body with muscles.",
  },
  {
    id: 44,
    spotter: "ABD-44",
    structureName: "Renal Sinus",
    questionA: "Identify the pinned structure.",
    questionB: "Give its contents.",
    answerA: "Renal sinus",
    answerB: "Contents: (1) Branches of renal artery. (2) Tributaries of renal vein. (3) Renal pelvis dividing into major and minor calyces, each indented by 1–3 renal papillae.",
  },
  {
    id: 45,
    spotter: "ABD-45",
    structureName: "Right Crus of Diaphragm",
    questionA: "Identify the pinned structure.",
    questionB: "Give its attachment.",
    answerA: "Right crus of diaphragm",
    answerB: "Attachment: from the anterolateral surface of the bodies of upper three lumbar vertebrae (L1–L3) and the intervening intervertebral discs.",
  },
  {
    id: 46,
    spotter: "ABD-46",
    structureName: "Spermatic Cord",
    questionA: "Identify the tied structure.",
    questionB: "Give its contents and coverings.",
    answerA: "Spermatic cord",
    answerB: "Contents: ductus deferens; testicular & cremasteric arteries and artery to vas deferens; pampiniform plexus; genital branch of genitofemoral nerve; remains of processus vaginalis; lymph vessels from testis. Coverings: (1) External spermatic fascia. (2) Cremasteric fascia. (3) Internal spermatic fascia.",
  },
  {
    id: 47,
    spotter: "ABD-47",
    structureName: "Suprarenal Glands",
    questionA: "Identify the GREEN and YELLOW coloured pinned structures.",
    questionB: "Give the blood supply of suprarenal glands.",
    answerA: "Yellow — right suprarenal gland; Green — left suprarenal gland",
    answerB: "Arterial supply: (1) Superior suprarenal artery (from inferior phrenic artery). (2) Middle suprarenal artery (from abdominal aorta). (3) Inferior suprarenal artery (from renal artery). Venous drainage: right suprarenal vein → IVC; left suprarenal vein → left renal vein.",
  },
  {
    id: 48,
    spotter: "ABD-48",
    structureName: "Testis",
    questionA: "Identify the side of the organ.",
    questionB: "Give its coverings, blood supply and applied anatomy.",
    answerA: "Right testis",
    answerB: "Coverings: (1) Tunica vaginalis. (2) Tunica albuginea. (3) Tunica vasculosa. Blood supply: testicular artery (branch of abdominal aorta); pampiniform plexus of veins. Applied anatomy: hydrocele, varicocele.",
  },
  {
    id: 49,
    spotter: "ABD-49",
    structureName: "Trigone of Urinary Bladder",
    questionA: "Identify the pinned structure.",
    questionB: "Give its development.",
    answerA: "Trigone of urinary bladder",
    answerB: "Development: formed by absorption of the mesonephric (Wolffian) ducts into the posterior wall of the urinary bladder.",
  },
  {
    id: 50,
    spotter: "ABD-50",
    structureName: "Ureter",
    questionA: "Identify the pinned structure.",
    questionB: "Give its constrictions, where it opens and applied anatomy.",
    answerA: "Ureter",
    answerB: "Constrictions: (1) Pelviureteric junction. (2) At brim of lesser pelvis. (3) Where crossed by vas deferens or broad ligament. (4) During oblique passage through bladder wall. (5) At opening into lateral angle of trigone. Termination: lateral angle of trigone of urinary bladder. Applied: ureteric colic, ureteric calculi.",
  },
  {
    id: 51,
    spotter: "ABD-51",
    structureName: "Uterine Tube",
    questionA: "Identify the tied structure.",
    questionB: "Give its parts, blood supply and applied anatomy.",
    answerA: "Uterine tube (Fallopian tube)",
    answerB: "Parts: infundibulum, ampulla, isthmus, uterine (intramural) part. Blood supply: uterine artery (medial ⅔), ovarian artery (lateral ⅓). Applied anatomy: salpingitis, tubal blockage, tubectomy.",
  },
  {
    id: 52,
    spotter: "ABD-52",
    structureName: "Uterus",
    questionA: "Identify the pinned structure.",
    questionB: "Give its normal anatomical position, parts, blood supply, supports and development.",
    answerA: "Uterus",
    answerB: "Position: anteversion (90°) and anteflexion (125°). Parts: fundus, body and cervix. Blood supply: uterine and ovarian arteries. Supports — primary muscular: pelvic diaphragm, perineal body, distal urethral sphincter; fibromuscular: pubocervical, transverse cervical (Mackenrodt), uterosacral, round ligaments. Development: paramesonephric (Müllerian) ducts.",
  },
  {
    id: 53,
    spotter: "ABD-53",
    structureName: "Uterus (Anterior View)",
    questionA: "Identify the pinned structure.",
    questionB: "Give its normal anatomical position, parts, blood supply, supports and development.",
    answerA: "Uterus — anterior view",
    answerB: "Position: anteversion (90°) and anteflexion (125°). Parts: fundus, body and cervix. Blood supply: uterine and ovarian arteries. Supports — primary muscular: pelvic diaphragm, perineal body; fibromuscular: pubocervical, transverse cervical (Mackenrodt), uterosacral, round ligaments. Secondary: broad ligaments, uterosacral fold, rectovaginal fold. Development: paramesonephric ducts.",
  },
  {
    id: 54,
    spotter: "ABD-54",
    structureName: "Penis",
    questionA: "Identify the pinned structure.",
    questionB: "Give its blood supply and name the erectile masses of tissue within it.",
    answerA: "Penis",
    answerB: "Blood supply: deep artery of penis, dorsal artery of penis, and artery to the bulb of penis (all from internal pudendal artery). Erectile masses: two corpora cavernosa (dorsal) and one corpus spongiosum (ventral, surrounding urethra).",
  },
  {
    id: 55,
    spotter: "ABD-55",
    structureName: "Quadratus Lumborum",
    questionA: "Identify the pinned structure.",
    questionB: "Give its attachments, nerve supply and actions.",
    answerA: "Quadratus lumborum",
    answerB: "Origin: transverse process of L5 vertebra. Insertion: transverse processes of upper 4 lumbar vertebrae and lower border of 12th rib. Nerve supply: ventral rami of T12–L4. Action: fixes the last rib during inspiration; lateral flexion of the vertebral column.",
  },
  {
    id: 56,
    spotter: "ABD-56",
    structureName: "Retropubic Space",
    questionA: "Identify the probed space.",
    questionB: "Give its contents.",
    answerA: "Retropubic space (Cave of Retzius)",
    answerB: "Contents: retropubic fat and vesical plexus of veins.",
  },
  {
    id: 56,
    spotter: "ABD-57",
    structureName: "Bare Area of Liver",
    questionA: "Identify the pinned area.",
    questionB: "Give its boundaries and applied anatomy.",
    answerA: "Bare area of liver",
    answerB: "Boundaries — superior: superior layer of coronary ligament; inferior: inferior layer of coronary ligament; right: right triangular ligament. Clinical importance: site of porto-systemic anastomosis.",
  },
  {
    id: 55,
    spotter: "ABD-58",
    structureName: "Right Kidney",
    questionA: "Identify the side of the organ.",
    questionB: "Give its anterior and posterior relations.",
    answerA: "Right kidney",
    answerB: "Anterior: right suprarenal gland, liver, 2nd part of duodenum, hepatic flexure, small intestine. Posterior: diaphragm, medial & lateral arcuate ligaments, psoas major, quadratus lumborum, transversus abdominis, subcostal vessels, subcostal / ilioinguinal / iliohypogastric nerves.",
  },
  {
    id: 54,
    spotter: "ABD-59",
    structureName: "Left Kidney",
    questionA: "Identify the side of the organ.",
    questionB: "Give its anterior and posterior relations.",
    answerA: "Left kidney",
    answerB: "Anterior: left suprarenal gland, spleen, stomach, pancreas, splenic vessels, splenic flexure & descending colon, jejunum. Posterior: diaphragm, medial & lateral arcuate ligaments, psoas major, quadratus lumborum, transversus abdominis, subcostal vessels, subcostal / ilioinguinal / iliohypogastric nerves.",
  },
  {
    id: 53,
    spotter: "ABD-60",
    structureName: "Urinary Bladder",
    questionA: "Identify the pinned structure.",
    questionB: "Give its supports, nerve supply and blood supply.",
    answerA: "Urinary bladder",
    answerB: "Supports — true: lateral, lateral puboprostatic, medial puboprostatic, posterior ligaments, median umbilical ligament; false: median umbilical fold, medial umbilical fold, lateral & posterior false ligaments. Nerve supply: parasympathetic (S2–S4), sympathetic (T11–L2), somatic — pudendal nerve. Blood supply: superior & inferior vesical arteries, obturator & inferior gluteal arteries.",
  },
];
