import { ImageSourcePropType } from "react-native";

export const NEURO_IMAGES: Record<number, ImageSourcePropType> = {
  1:  require("../assets/images/neuro/na001_anterolateral_sulcus.png"),
  2:  require("../assets/images/neuro/na002_basilar_artery.png"),
  3:  require("../assets/images/neuro/na003_basilar_sulcus.png"),
  4:  require("../assets/images/neuro/na004_cauda_equina.png"),
  5:  require("../assets/images/neuro/na005_central_sulcus.png"),
  6:  require("../assets/images/neuro/na006_cerebellum.png"),
  7:  require("../assets/images/neuro/na007_cerebral_peduncle.png"),
  8:  require("../assets/images/neuro/na008_filum_terminale.png"),
  9:  require("../assets/images/neuro/na009_inf_cerebellar_peduncle.png"),
  10: require("../assets/images/neuro/na010_interpeduncular_fossa.png"),
  11: require("../assets/images/neuro/na011_internal_capsule.png"),
  12: require("../assets/images/neuro/na012_internal_carotid_artery.png"),
  13: require("../assets/images/neuro/na013_ligamentum_denticulatum.png"),
  14: require("../assets/images/neuro/na014_mid_cerebellar_peduncle.png"),
  15: require("../assets/images/neuro/na015_brocas_area.png"),
  16: require("../assets/images/neuro/na016_olive.png"),
  17: require("../assets/images/neuro/na017_pons.png"),
  18: require("../assets/images/neuro/na018_pontomedullary_junction.png"),
  19: require("../assets/images/neuro/na019_postcentral_gyrus.png"),
  20: require("../assets/images/neuro/na020_lateral_sulcus.png"),
  21: require("../assets/images/neuro/na021_posterolateral_sulcus.png"),
  22: require("../assets/images/neuro/na022_precentral_gyrus.png"),
  23: require("../assets/images/neuro/na023_pyramid.png"),
  24: require("../assets/images/neuro/na024_wernickes_area.png"),
  25: require("../assets/images/neuro/na025_spinal_cord.png"),
  26: require("../assets/images/neuro/na026_superior_temporal_gyrus.png"),
};
