import { ImageSourcePropType } from "react-native";

export const UPPER_LIMB_IMAGES: Record<number, ImageSourcePropType> = {
  1:  require("../assets/images/upper-limb/specimen_01.jpg"),
  2:  require("../assets/images/upper-limb/specimen_02.jpg"),
  3:  require("../assets/images/upper-limb/specimen_03.jpg"),
  4:  require("../assets/images/upper-limb/specimen_04.jpg"),
  5:  require("../assets/images/upper-limb/specimen_05.jpg"),
  6:  require("../assets/images/upper-limb/specimen_06.jpg"),
  7:  require("../assets/images/upper-limb/specimen_07.jpg"),
  8:  require("../assets/images/upper-limb/specimen_08.jpg"),
  9:  require("../assets/images/upper-limb/specimen_09.jpg"),
  10: require("../assets/images/upper-limb/specimen_10.jpg"),
  11: require("../assets/images/upper-limb/specimen_11.jpg"),
  12: require("../assets/images/upper-limb/specimen_12.jpg"),
  13: require("../assets/images/upper-limb/specimen_13.jpg"),
  14: require("../assets/images/upper-limb/specimen_14.jpg"),
  15: require("../assets/images/upper-limb/specimen_15.jpg"),
  16: require("../assets/images/upper-limb/specimen_16.jpg"),
  17: require("../assets/images/upper-limb/specimen_17.jpg"),
  18: require("../assets/images/upper-limb/specimen_18.jpg"),
  19: require("../assets/images/upper-limb/specimen_19.jpg"),
  20: require("../assets/images/upper-limb/specimen_20.jpg"),
  21: require("../assets/images/upper-limb/specimen_21.jpg"),
  22: require("../assets/images/upper-limb/specimen_22.jpg"),
  23: require("../assets/images/upper-limb/specimen_23.jpg"),
  24: require("../assets/images/upper-limb/specimen_24.jpg"),
  25: require("../assets/images/upper-limb/specimen_25.jpg"),
  26: require("../assets/images/upper-limb/specimen_26.jpg"),
  27: require("../assets/images/upper-limb/specimen_27.jpg"),
  28: require("../assets/images/upper-limb/specimen_28.jpg"),
  29: require("../assets/images/upper-limb/specimen_29.jpg"),
  30: require("../assets/images/upper-limb/specimen_30.jpg"),
};
